#!/system/bin/sh

############################
# Intelli_Plug
#
echo "1" > /sys/kernel/intelli_plug/intelli_plug_active
# 0:"Balanced", 1:"Performance", 2:"Conservative", 3:"Disabled", 4:"Tri", 5:"Eco", 6:"Strict"
echo "0" > /sys/kernel/intelli_plug/full_mode_profile
echo "8" > /sys/kernel/intelli_plug/nr_run_hysteresis
echo "722" > /sys/kernel/intelli_plug/cpu_nr_run_threshold
echo "1" > /sys/kernel/intelli_plug/debug_intelli_plug
echo "0" > /sys/kernel/intelli_plug/hotplug_suspend
echo "2" > /sys/kernel/intelli_plug/cpus_boosted
echo "1" > /sys/kernel/intelli_plug/min_cpus_online
echo "4" > /sys/kernel/intelli_plug/max_cpus_online
echo "10" > /sys/kernel/intelli_plug/suspend_defer_time
echo "30" > /sys/kernel/intelli_plug/def_sampling_ms
echo "500" > /sys/kernel/intelli_plug/boost_lock_duration
echo "2000" > /sys/kernel/intelli_plug/down_lock_duration
echo "3" > /sys/kernel/intelli_plug/nr_fshift

############################
# MSM Limiter
#
echo "1" > /sys/kernel/msm_limiter/limiter_enabled
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_0
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_1
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_2
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_3
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_0
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_1
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_2
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_3
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_0
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_1
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_2
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_3
echo "1728000" > /sys/kernel/msm_limiter/suspend_max_freq

############################
# Governor Tunings
#
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_0
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_1
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_2
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_3

#Ondemand
echo "95" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold
echo "50000" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_rate
echo "1" > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
echo "4" > /sys/devices/system/cpu/cpufreq/ondemand/sampling_down_factor
echo "10" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential
echo "75" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_multi_core
echo "3" > /sys/devices/system/cpu/cpufreq/ondemand/down_differential_multi_core
echo "960000" > /sys/devices/system/cpu/cpufreq/ondemand/optimal_freq
echo "960000" > /sys/devices/system/cpu/cpufreq/ondemand/sync_freq
echo "85" > /sys/devices/system/cpu/cpufreq/ondemand/up_threshold_any_cpu_load

#Interactive
echo "20000 1400000:40000 1700000:20000" > /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
echo "90" > /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
echo "1190400" > /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
echo "1" > /sys/devices/system/cpu/cpufreq/interactive/io_is_busy
echo "85 1500000:90 1800000:70" > /sys/devices/system/cpu/cpufreq/interactive/target_loads
echo "40000" > /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
echo "30000" > /sys/devices/system/cpu/cpufreq/interactive/timer_rate
echo "30000" > /sys/devices/system/cpu/cpufreq/interactive/timer_slack

############################
# Scheduler and Read Ahead
#
echo "row" > /sys/block/mmcblk0/queue/scheduler
echo "512" > /sys/block/mmcblk0/bdi/read_ahead_kb

############################
# Bricked Thermal Controls
#
echo "68" > /sys/kernel/msm_thermal/conf/allowed_low_high
echo "65" > /sys/kernel/msm_thermal/conf/allowed_low_low
echo "1497600" > /sys/kernel/msm_thermal/conf/allowed_low_freq 
echo "75" > /sys/kernel/msm_thermal/conf/allowed_mid_high 
echo "69" > /sys/kernel/msm_thermal/conf/allowed_mid_low 
echo "960000" > /sys/kernel/msm_thermal/conf/allowed_mid_freq 
echo "81" > /sys/kernel/msm_thermal/conf/allowed_max_high 
echo "76" > /sys/kernel/msm_thermal/conf/allowed_max_low
echo "300000" > /sys/kernel/msm_thermal/conf/allowed_max_freq 
echo "400" > /sys/kernel/msm_thermal/conf/poll_ms 
echo "82" > /sys/kernel/msm_thermal/conf/shutdown_temp 

############################
# GPU
#
echo "450000000" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk
echo "msm-adreno-tz" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/governor
# Simple gpu algorithm
echo "1" > /sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate
echo "4" > /sys/module/simple_gpu_algorithm/parameters/simple_laziness
echo "5000" > /sys/module/simple_gpu_algorithm/parameters/simple_ramp_threshold

############################
# Power Suspend
#
# Power Suspend Mode: "0" Kernel Mode, "1" User Mode, "2" LCD Hooks
# Power Suspend State: Kernel power management driver when screen is off. You can only change this setting if Power Suspend Mode is in User Mode.
#
echo "0" > /sys/kernel/power_suspend/power_suspend_mode
echo "0" > /sys/kernel/power_suspend/power_suspend_state

############################
# Backlight Control
#
echo "Y" > /sys/module/lm3630/parameters/lm3630_min_backlight_reducer
echo "60" > /sys/module/lm3630/parameters/lm3630_min_backlight_set

############################
# KCAL color control
#
echo "1" > /sys/devices/platform/kcal_ctrl.0/kcal_enable
#(0-256) - Controls minimum RGB Multiplier value
echo "1" > /sys/devices/platform/kcal_ctrl.0/kcal_min
#(0-256 0-256 0-256) - Controls R/G/B Multipliers
echo "256 256 256" > /sys/devices/platform/kcal_ctrl.0/kcal
#(0-1) - Enables/Disables Display Inversion Mode
echo "0" > /sys/devices/platform/kcal_ctrl.0/kcal_invert
#(224-383 or 128) - Controls saturation intensity - use 128 for grayscale mode
echo "268" > /sys/devices/platform/kcal_ctrl.0/kcal_sat
#(0-1536) - Controls display hue
echo "0" > /sys/devices/platform/kcal_ctrl.0/kcal_hue
#(128-383) - Controls display value
echo "255" > /sys/devices/platform/kcal_ctrl.0/kcal_val
#(128-383) - Controls display contrast
echo "255" > /sys/devices/platform/kcal_ctrl.0/kcal_cont

############################
# SoundControl
#
echo "10" > /sys/devices/virtual/misc/soundcontrol/volume_boost
echo "2" > /sys/devices/virtual/misc/soundcontrol/speaker_boost
echo "0" > /sys/devices/virtual/misc/soundcontrol/mic_boost
echo "0" > /sys/devices/virtual/misc/soundcontrol/camera_mic_boost

############################
# Fsync control
#
echo “N” > /sys/module/sync/parameters/fsync_enabled

############################
# Logger Mode
# "0" Enabled, "1" Auto suspend, "2" Disabled
echo "1" > /sys/module/logger/parameters/log_mode

############################
# USB Fast charge
#
echo "1" > /sys/kernel/fast_charge/force_fast_charge
echo "1200" > /sys/kernel/fast_charge/fast_charge_level

############################
# Power Effecient Workqueues
#
echo "Y" > /sys/module/workqueue/parameters/power_efficient

############################
# Tweak Background Writeout
#
echo "200" > /proc/sys/vm/dirty_expire_centisecs
echo "40" > /proc/sys/vm/dirty_ratio
echo "5" > /proc/sys/vm/dirty_background_ratio
echo "10" > /proc/sys/vm/swappiness

############################
# LMK Tweaks
#
echo "2560,4096,8192,16384,24576,32768" > /sys/module/lowmemorykiller/parameters/minfree
echo "32" > /sys/module/lowmemorykiller/parameters/cost

