#!/system/bin/sh

############################
# Intelli_Plug
#
echo "1" > /sys/kernel/intelli_plug/intelli_plug_active
# 0:"Balanced", 1:"Performance", 2:"Conservative", 3:"Disabled", 4:"Tri", 5:"Eco", 6:"Strict"
echo "0" > /sys/kernel/intelli_plug/full_mode_profile
echo "8" > /sys/kernel/intelli_plug/nr_run_hysteresis
echo "722" > /sys/kernel/intelli_plug/cpu_nr_run_threshold
echo "1" > /sys/kernel/intelli_plug/debug_intelli_plug
echo "0" > /sys/kernel/intelli_plug/hotplug_suspend
echo "2" > /sys/kernel/intelli_plug/cpus_boosted
echo "1" > /sys/kernel/intelli_plug/min_cpus_online
echo "4" > /sys/kernel/intelli_plug/max_cpus_online
echo "10" > /sys/kernel/intelli_plug/suspend_defer_time
echo "30" > /sys/kernel/intelli_plug/def_sampling_ms
echo "500" > /sys/kernel/intelli_plug/boost_lock_duration
echo "2000" > /sys/kernel/intelli_plug/down_lock_duration
echo "3" > /sys/kernel/intelli_plug/nr_fshift

############################
# MSM Limiter
#
echo "1" > /sys/kernel/msm_limiter/limiter_enabled
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_0
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_1
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_2
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_3
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_0
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_1
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_2
echo "2265600" > /sys/kernel/msm_limiter/resume_max_freq_3
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_0
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_1
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_2
echo "2265600" > /sys/kernel/msm_limiter/live_max_freq_3
echo "1728000" > /sys/kernel/msm_limiter/suspend_max_freq

############################
# Governor Tunings
#
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_0
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_1
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_2
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_3

############################
# Scheduler and Read Ahead
#
echo "row" > /sys/block/mmcblk0/queue/scheduler
echo "512" > /sys/block/mmcblk0/bdi/read_ahead_kb

############################
# GPU
#
echo "450000000" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk
echo "msm-adreno-tz" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/governor
# Simple gpu algorithm
echo "1" > /sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate
echo "4" > /sys/module/simple_gpu_algorithm/parameters/simple_laziness
echo "5000" > /sys/module/simple_gpu_algorithm/parameters/simple_ramp_threshold

