#!/system/bin/sh

############################
# Intelli_Plug
#
echo "1" > /sys/kernel/intelli_plug/intelli_plug_active
# 0:"Balanced", 1:"Performance", 2:"Conservative", 3:"Disabled", 4:"Tri", 5:"Eco", 6:"Strict"
echo "1" > /sys/kernel/intelli_plug/full_mode_profile
echo "2" > /sys/kernel/intelli_plug/cpus_boosted
echo "2" > /sys/kernel/intelli_plug/min_cpus_online
echo "4" > /sys/kernel/intelli_plug/max_cpus_online

############################
# MSM Limiter
#
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_0
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_1
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_2
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_3
echo "2572800" > /sys/kernel/msm_limiter/resume_max_freq_0
echo "2572800" > /sys/kernel/msm_limiter/resume_max_freq_1
echo "2572800" > /sys/kernel/msm_limiter/resume_max_freq_2
echo "2572800" > /sys/kernel/msm_limiter/resume_max_freq_3
echo "2572800" > /sys/kernel/msm_limiter/live_max_freq_0
echo "2572800" > /sys/kernel/msm_limiter/live_max_freq_1
echo "2572800" > /sys/kernel/msm_limiter/live_max_freq_2
echo "2572800" > /sys/kernel/msm_limiter/live_max_freq_3
echo "1728000" > /sys/kernel/msm_limiter/suspend_max_freq

############################
# Governor Tunings
#
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_0
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_1
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_2
echo "interactive" > /sys/kernel/msm_limiter/scaling_governor_3 

############################
# Scheduler and Read Ahead
#
echo "deadline" > /sys/block/mmcblk0/queue/scheduler
echo "512" > /sys/block/mmcblk0/bdi/read_ahead_kb

############################
# GPU Governor
#
echo "450000000" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk
echo "msm-adreno-tz" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/governor
# Simple gpu algorithm
echo "1" > /sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate
echo "4" > /sys/module/simple_gpu_algorithm/parameters/simple_laziness
echo "5000" > /sys/module/simple_gpu_algorithm/parameters/simple_ramp_threshold

