#!/system/bin/sh

############################
# Intelli_Plug
#
echo "1574400" > /sys/module/intelli_plug/parameters/screen_off_max
echo "0" > /sys/module/intelli_plug/parameters/touch_boost_active
# 0:"Balanced (4)", 1:"Performance (4)", 2:"Conservative (4)", 3:"Eco Performance (2)", 4:"Eco Conservative (2)
echo "3" > /sys/module/intelli_plug/parameters/nr_run_profile_sel

############################
# MSM Limiter
#
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_0
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_1
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_2
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_3
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_0
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_1
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_2
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_3
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_0
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_1
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_2
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_3
echo "1574400" > /sys/kernel/msm_limiter/suspend_max_freq

############################
# Governor Tunings
#
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_0
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_1
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_2
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_3 

############################
# Scheduler and Read Ahead
#
echo "cfq" > /sys/block/mmcblk0/queue/scheduler
echo "512" > /sys/block/mmcblk0/bdi/read_ahead_kb

############################
# GPU Governor
#
echo "389000000" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk
echo "conservative" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/governor
echo "0" > /sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate
# Conservative Governor
echo "20" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/gpufreq/conservative/downthreshold
echo "50" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/gpufreq/conservative/upthreshold_cons

