#!/system/bin/sh

############################
# Intelli_Plug
#
echo "1" > /sys/kernel/intelli_plug/intelli_plug_active
# 0:"Balanced", 1:"Performance", 2:"Conservative", 3:"Disabled", 4:"Tri", 5:"Eco", 6:"Strict"
echo "2" > /sys/kernel/intelli_plug/full_mode_profile
echo "8" > /sys/kernel/intelli_plug/nr_run_hysteresis
echo "722" > /sys/kernel/intelli_plug/cpu_nr_run_threshold
echo "1" > /sys/kernel/intelli_plug/debug_intelli_plug
echo "0" > /sys/kernel/intelli_plug/hotplug_suspend
echo "2" > /sys/kernel/intelli_plug/cpus_boosted
echo "1" > /sys/kernel/intelli_plug/min_cpus_online
echo "2" > /sys/kernel/intelli_plug/max_cpus_online
echo "10" > /sys/kernel/intelli_plug/suspend_defer_time
echo "30" > /sys/kernel/intelli_plug/def_sampling_ms
echo "500" > /sys/kernel/intelli_plug/boost_lock_duration
echo "2000" > /sys/kernel/intelli_plug/down_lock_duration
echo "3" > /sys/kernel/intelli_plug/nr_fshift

############################
# MSM Limiter
#
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_0
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_1
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_2
echo "300000" > /sys/kernel/msm_limiter/suspend_min_freq_3
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_0
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_1
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_2
echo "1958400" > /sys/kernel/msm_limiter/resume_max_freq_3
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_0
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_1
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_2
echo "1958400" > /sys/kernel/msm_limiter/live_max_freq_3
echo "1574400" > /sys/kernel/msm_limiter/suspend_max_freq

############################
# Governor Tunings
#
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_0
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_1
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_2
echo "conservative" > /sys/kernel/msm_limiter/scaling_governor_3 

############################
# Scheduler and Read Ahead
#
echo "cfq" > /sys/block/mmcblk0/queue/scheduler
echo "512" > /sys/block/mmcblk0/bdi/read_ahead_kb

############################
# GPU Governor
#
echo "389000000" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/max_gpuclk
echo "conservative" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/governor
echo "0" > /sys/module/simple_gpu_algorithm/parameters/simple_gpu_activate
# Conservative Governor
echo "20" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/gpufreq/conservative/downthreshold
echo "50" > /sys/devices/fdb00000.qcom,kgsl-3d0/kgsl/kgsl-3d0/devfreq/gpufreq/conservative/upthreshold_cons

